set nocompatible              " be iMproved, required
filetype off                  " required

" Put your non-Plugin stuff after this line

syntax on
set ruler
set ic
set ai
set magic
set sm
set number
"set expandtab
set noet ci pi sts=0 sw=4 ts=4
set listchars=eol:$,tab:>.,trail:~,extends:>,precedes:<,nbsp:%
set cursorline
hi CursorLine term=bold cterm=NONE ctermbg=234
set hlsearch
nnoremap <C-l> :nohl<CR><C-L>
set backspace=2

" Enable Mouse Support
if has('mouse')
   set mouse=a
endif

" Return to last edit position when opening files
if has("autocmd")
   au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" For Different Cursor Shapes in Vim Editor. This works inside tmux.
"    - t_SI = Insert Mode
"    - t_SR = Replace Mode
"    - t_EI = Exit Insert Mode
"    - CursorShape
"        0 = bar
"        1 = vertical line
"        2 = underscore
let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
let &t_SR = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=2\x7\<Esc>\\"
let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"

